clear; clc; close all;
R = linspace(5,200,10);
Qd = 1e-9;
U0 = 0.02;       
gamma = 0.002;  
D0_DOX = 200; n_DOX = 0.35;
D0_CUR = 210; n_CUR = 0.28;
D0_TAM = 220; n_TAM = 0.22;
um = 1e-6; 
D_DOX = D0_DOX * (R.^(-n_DOX)) * um;
D_CUR = D0_CUR * (R.^(-n_CUR)) * um;
D_TAM = D0_TAM * (R.^(-n_TAM)) * um;
V_DOX = pi/6 * D_DOX.^3;
V_CUR = pi/6 * D_CUR.^3;
V_TAM = pi/6 * D_TAM.^3;
f_DOX = Qd ./ V_DOX;
f_CUR = Qd ./ V_CUR;
f_TAM = Qd ./ V_TAM;
U_R = U0 * (1 + gamma * R);
S_DOX = (U_R ./ f_DOX) * 1e6;  
S_CUR = (U_R ./ f_CUR) * 1e6;
S_TAM = (U_R ./ f_TAM) * 1e6;
figure('Color','w','Position',[200 200 900 450]);
% (1) Frequency vs Flow Ratio
subplot(1,2,1);
plot(R,f_DOX,'-o','LineWidth',2,'MarkerSize',6); hold on;
plot(R,f_CUR,'-s','LineWidth',2,'MarkerSize',6);
plot(R,f_TAM,'-^','LineWidth',2,'MarkerSize',6);
xlabel('Flow Rate Ratio (Q_c / Q_d)');
ylabel('Droplet Generation Frequency (Hz)');
title('Droplet Generation Frequency vs Q_c/Q_d');
legend('DOX (PLGA–PEG)','Curcumin (PCL–PEG)','Tamoxifen (PLGA)','Location','northwest');
grid on; set(gca,'FontSize',11);
% (2) DropSpacing vs Flow Ratio
subplot(1,2,2);
plot(R,S_DOX,'-o','LineWidth',2,'MarkerSize',6); hold on;
plot(R,S_CUR,'-s','LineWidth',2,'MarkerSize',6);
plot(R,S_TAM,'-^','LineWidth',2,'MarkerSize',6);
xlabel('Flow Rate Ratio (Q_c / Q_d)');
ylabel('Droplet Center Spacing (\mum)');
title('Droplet Spacing vs Q_c/Q_d');
legend('DOX','Curcumin','Tamoxifen','Location','northeast');
grid on; set(gca,'FontSize',11);
sgtitle('Droplet Frequency and Spacing vs Flow-Rate Ratio','FontSize',12,'FontWeight','bold');